import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/SideBar/SideBar";

//Cambiar al terminar
export const metadata: Metadata = {
  title: "Portfolio Marcelo Mastroiani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
